mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    path('',views.layout,name ='layout'),


]

polls/urls.py
from django.urls import path
from . import views
from polls import views as polls_views
from django.contrib.auth import views as auth_views

app_name = 'polls'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/',views.ResultView.as_view(), name='result'),
    path('<int:question_id>/votes/',views.votes, name='votes'),
    path('Register/',polls_views.Register, name= "Register"),
    path('login/',auth_views.login,{'template_name': 'polls/login.html'}, name='login'),
    path('logout/',auth_views.logout,{'template_name': 'polls/logout.html'}, name='logout'),

]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
         return self.question_text

    def was_published_recently(self):
        now=timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub-date<= now

class Choice(models.Model):
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
         return self.choice_text

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name= forms.CharField(max_length=30, required=False,help_text='Optional.')
    last_name= forms.CharField(max_length=30, required=False,help_text='Optional.')
    email= forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    password1 = forms.CharField(max_length=30, help_text="Required.",label="Password",widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=30, help_text="Required. It must match with above password",label='Confirm password', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', )

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from . models import Question, Choice
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from polls.forms import RegisterForm
# Create your views here.
class IndexView(generic.ListView):
    template_name="polls/index.html"
    context_object_name="latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

def layout(request):
    return render(request,'polls/layout.html')


def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))


def Register(request):
    if request.method =="POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get("username")
            raw_password=form.cleaned_data.get("password1")
            user=authenticate(username=username, password=raw_password)
            login(request,user)
            return HttpResponseRedirect(reverse('layout'))

    else:
        form=RegisterForm()
    return render(request,'polls/Register.html',{'form':form})
'''
def login(request):
    return render(request,'polls/login.html',{'form':form})
'''

polls/templates/polls/Register.html
{% extends 'polls/layout.html' %}
{% block content %}

<div class="container-fluid">
  <h2>Register</h2>
 </br>
   <form method="post">
     {% csrf_token %}
     {% for field in form %}
     <p>
     {{field.label_tag }}<br>
     {{field}}
     {% if field.help_text %}

     <small style="color: green">{{field.help_text}}</small>

     {% endif %}
     {% for error in field.errors %}
       <p style="color: red">{{error}}</p>
     {% endfor %}
   </p>
   {% endfor %}

     <button type="submit">Register</button>

   </form>
</div>

{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/layout.html' %}
{% block content %}
<div style="margin-top:200px;" align="center">

  <h1>{{question.question_text}}</h1>
  {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
  <form action="{% url 'polls:votes' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
      <input type='radio' name='choice' id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
      <input type="submit" value="Vote" />
      </form>

</div>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/layout.html' %}

{% block content %}<!-- default content text (typically empty) -->
<div style="margin-top:200px;" align="center">
            {% if latest_question_list %}
              <ul style="max-width:400px;margin:0 auto;">
                {% for question in latest_question_list %}
                <h2><li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li></h2>
                </br>
                  {% endfor %}
              </ul>
              {% else %}
                <p>No polls are available.</p>
              {% endif %}
            </div>
{% endblock %}

polls/templates/polls/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>POLLING SITE</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body style="background-color:LightGray  " >
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/admin/">Staff User</a>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="/polls/">Question</a>
    </li>
    {% else %}
    <li class="nav-item ">
      <a class="nav-link disabled" href="#">Question</a>
    </li>
    {% endif %}
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/polls/Register/">Register</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="/polls/logout/">Logout</a>
    </li>
    {% else %}
    <li class="nav-item active">
      <a class="nav-link" href="/polls/login/">Login</a>
    </li>
    {% endif %}
  </ul>
</nav>

      {% block content %}
        <div style="background:lightslategray !important" class="jumbotron jumbotron-fluid" >
              <div class="text-center">
                  <h1 class='display-2' >POLLING</h1>
              </div>

            </div>

        <div class="text-center">
        <div class="text-info">
          <h1 class='display-5' >This is polling app where you can Vote to various question's choice and get results of each questions!!</h1>


        </div>
        {% endblock %}

    </div>


</body>
</html>

polls/templates/polls/login.html
{% extends "polls/layout.html" %}

{% block content %}
<div style="margin-top:100px;" align="center">
  <h1>Welcome to Login page</h1>
</br>
  <p> Here you can login!</p>
  </br>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Login</button>
    </form>
    </br>
    <p>If you don't have account!!</p>

    <a href="{% url 'polls:Register' %}">Register here!</a>


</div>

{% endblock %}

polls/templates/polls/logout.html
{% extends "polls/layout.html" %}

{% block content %}
<div style="margin-top:100px;" align="center">
  <h1>Logout</h1>
</br>
  <p>You have successfully logout!! </p>
  </br>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    </form>
    <p>If you want to login?</p>

    <a href="{% url 'polls:login' %}">Login here!</a>


</div>
</div>

{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/layout.html' %}
{% block content %}
<div style="margin-top:200px" align="center">
    <h1>{{question.question_text}}</h1>
    <ol style="max-width:200px;margin:0 auto;" >
     {% for choice in question.choice_set.all %}
     <li>
       {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}

     </li>
     {% endfor %}
   </ol>
     <a href="{%url 'polls:detail' question.id %}">Vote Again?</a>
</div>
{% endblock %}